@echo off
setlocal enabledelayedexpansion
cls

REM Pacificia Setup Script for Windows
echo.
echo  ____             _  __ _      _       
echo ^|  _ \ __ _  __ _(_)/ _(_) ___(_) __ _ 
echo ^| ^|_) / _` ^|/ _` ^| ^| ^|_^| ^|/ __^| ^|/ _` ^|
echo ^|  __/ (_^| ^| (_^| ^| ^|  _^| ^| (__^| ^| (_^| ^|
echo ^|_^|   \__,_^|\__,_^|_^|_^| ^|_^|\___^|_^|\__,_^|
echo.
echo ========================================
echo    Installing Pacificia AI Assistant
echo ========================================
echo.

REM Step 1: Check Python
echo [1/6] Checking Python installation...
python --version >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python is not installed or not in PATH!
    echo.
    echo Please install Python 3.8 or higher from:
    echo   https://www.python.org/downloads/
    echo.
    echo IMPORTANT: During installation, check:
    echo   [X] Add Python to PATH
    echo.
    pause
    exit /b 1
)

for /f "tokens=2" %%i in ('python --version 2^>^&1') do set PYTHON_VERSION=%%i
echo       [OK] Found Python %PYTHON_VERSION%

REM Check Python version
python -c "import sys; exit(0 if sys.version_info >= (3, 8) else 1)" >nul 2>&1
if errorlevel 1 (
    echo [ERROR] Python 3.8 or higher is required!
    echo You have: %PYTHON_VERSION%
    pause
    exit /b 1
)

REM Step 2: Virtual environment
echo.
echo [2/6] Setting up virtual environment...
if exist env (
    echo       [OK] Using existing virtual environment
) else (
    python -m venv env
    if errorlevel 1 (
        echo [ERROR] Failed to create virtual environment
        pause
        exit /b 1
    )
    echo       [OK] Virtual environment created
)

REM Step 3: Activate environment
echo.
echo [3/6] Activating virtual environment...
call env\Scripts\activate.bat
if errorlevel 1 (
    echo [ERROR] Failed to activate virtual environment
    pause
    exit /b 1
)
echo       [OK] Virtual environment activated

REM Step 4: Upgrade pip
echo.
echo [4/6] Upgrading pip...
python -m pip install --upgrade pip --quiet
if errorlevel 1 (
    echo [WARNING] Pip upgrade failed, continuing anyway...
) else (
    echo       [OK] Pip upgraded
)

REM Step 5: Install dependencies
echo.
echo [5/6] Installing dependencies...
if not exist requirements.txt (
    echo [ERROR] requirements.txt not found!
    pause
    exit /b 1
)

echo       Installing: rich, requests, python-dotenv, pyfiglet...
pip install -r requirements.txt --quiet
if errorlevel 1 (
    echo [ERROR] Failed to install dependencies
    echo.
    echo Try manually: pip install -r requirements.txt
    pause
    exit /b 1
)
echo       [OK] All dependencies installed

REM Step 6: Create .env file
echo.
echo [6/6] Setting up environment variables...
if not exist .env (
    if exist .env.example (
        copy .env.example .env >nul
        echo       [OK] Created .env from template
    ) else (
        echo # Pacificia Configuration > .env
        echo GROQ_API_KEY=your_groq_api_key_here >> .env
        echo       [OK] Created .env file
    )
    
    echo.
    echo ========================================
    echo    ACTION REQUIRED: API Key Setup
    echo ========================================
    echo.
    echo Pacificia needs a Groq API key to work.
    echo.
    echo Steps:
    echo   1. Get your FREE API key from:
    echo      https://console.groq.com/keys
    echo.
    echo   2. Copy the key (starts with 'gsk_...')
    echo.
    echo   3. Replace 'your_groq_api_key_here' in .env
    echo.
    
    set /p OPEN_NOW="Open .env in Notepad now? (Y/N): "
    if /i "!OPEN_NOW!"=="Y" (
        start notepad .env
        echo.
        echo Waiting for you to save and close Notepad...
        echo.
    ) else (
        echo.
        echo Remember to edit .env before running Pacificia:
        echo   notepad .env
        echo.
    )
) else (
    echo       [OK] .env file already exists
    
    REM Check if API key is set
    findstr /C:"your_groq_api_key_here" .env >nul 2>&1
    if not errorlevel 1 (
        echo       [!] API key not configured yet
        echo       Edit .env and add your Groq API key
    )
)

REM Create simple launcher
echo.
echo Creating launcher script...
echo @echo off > pacificia.bat
echo REM Pacificia launcher - Auto-generated by setup.bat >> pacificia.bat
echo cd /d "%%~dp0" >> pacificia.bat
echo call env\Scripts\activate.bat >> pacificia.bat
echo if errorlevel 1 ( >> pacificia.bat
echo     echo Error: Virtual environment not found! >> pacificia.bat
echo     echo Run setup.bat again >> pacificia.bat
echo     pause >> pacificia.bat
echo     exit /b 1 >> pacificia.bat
echo ) >> pacificia.bat
echo python pacificia.py %%* >> pacificia.bat
echo       [OK] Created pacificia.bat

echo.
echo ========================================
echo    Installation Complete!
echo ========================================
echo.

REM Verify API key configuration
set API_CONFIGURED=0
if exist .env (
    findstr /C:"your_groq_api_key_here" .env >nul 2>&1
    if errorlevel 1 (
        set API_CONFIGURED=1
    )
)

if !API_CONFIGURED!==1 (
    echo [OK] API key is configured
    echo.
) else (
    echo [!] API Key Not Configured Yet
    echo.
    echo Before running Pacificia, edit:
    echo   notepad .env
    echo.
    echo Get your key: https://console.groq.com/keys
    echo.
)

echo How to run Pacificia:
echo.
echo   Option 1 (Recommended):
echo     pacificia.bat
echo.
echo   Option 2 (Direct):
echo     python pacificia.py
echo.
echo   Option 3 (From anywhere - Advanced):
echo     Add this folder to your PATH environment variable
echo     Then run 'pacificia.bat' from any directory
echo.
echo ----------------------------------------
echo Happy chatting!
echo ----------------------------------------
echo.

REM Test if launcher works
echo Testing launcher...
if exist pacificia.bat (
    echo [OK] Launcher is ready
) else (
    echo [!] Launcher creation failed
)

echo.
pause
